apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  resource.customizations: |
    # Ignores .data changes of all secrets with a vaultInjectionChecksum annotation
    argoproj.io/Application:
     ignoreDifferences: |
        jqPathExpressions:
          - '. | select(.metadata.annotations.helmParametersChecksum) | .spec.source.helm'
    # Ignores caBundle and template changes of the following resources
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
          - .metadata.annotations.template
          - '.webhooks[]?.clientConfig.caBundle'
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jqPathExpressions:
          - .spec.conversion.webhookClientConfig.caBundle
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
          - .metadata.annotations.template
          - '.webhooks[]?.clientConfig.caBundle'
    cert-manager.io/Certificate:
      ignoreDifferences: |
        jqPathExpressions:
          - .spec.duration
  url: https://argocd.example.com
