apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
spec:
  entryPoints:
    - internalhttps
  routes:
    - kind: Rule
      match: {{.Values.hostPrefixRegex}} && PathPrefix(`/argocd`)
      services:
        - kind: Service
          name: argocd-server
          namespace: {{.Release.Namespace}}
          passHostHeader: true
          port: 80